services:

  devcontainer:
    build:
      context: .
      dockerfile: ./docker/Devcontainer.Dockerfile
      args:
        USER_NAME: ${DEVCONTAINER_USER_NAME}
        USER_ID: ${DEVCONTAINER_USER_ID}
        GROUP_ID: ${DEVCONTAINER_GROUP_ID}
    working_dir: /workspace
    tty: true
    stdin_open: true
    env_file: .env
    volumes:
      - ./:/workspace/:cached
    command: sleep infinity
