services:

  devcontainer:
    build:
      context: .
      dockerfile: ./docker/Devcontainer.Dockerfile
      args:
        USER_NAME: ${DEVCONTAINER_USER_NAME}
        USER_ID: ${DEVCONTAINER_USER_ID}
        GROUP_ID: ${DEVCONTAINER_GROUP_ID}
    working_dir: /workspace
    tty: true
    stdin_open: true
    env_file: .env
    volumes:
      - ./:/workspace/:cached
    command: sleep infinity

  vitepress:
    build:
      context: .
      dockerfile: ./docker/VitePress.Dockerfile
    environment:
      - NODE_ENV=development
      - PORT=5173
    ports:
      - 5173:5173
    volumes:
      - ./docs/rdd:/app
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]
    env_file: .env
